import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useRealtime } from '../../context/RealtimeContext';
import { useAuth } from '../../context/AuthContext';
import { Header } from '../../components/layout/Header';
import { Sidebar } from '../../components/layout/Sidebar';
import { ShieldAlert, CheckCircle2, Eye, Check, Clock, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

export const DoctorAlertsPage: React.FC = () => {
  const { alerts, acknowledgeAlert, clearAllAlerts, getPatientById } = useRealtime();
  const { user } = useAuth();
  const navigate = useNavigate();

  const [selectedPriority, setSelectedPriority] = useState<string>('ALL');
  const [selectedStatus, setSelectedStatus] = useState<string>('ALL');

  const filteredAlerts = alerts.filter((a) => {
    const matchesPriority = selectedPriority === 'ALL' || a.priority === selectedPriority;
    const matchesStatus = selectedStatus === 'ALL' || a.status === selectedStatus;
    return matchesPriority && matchesStatus;
  });

  const doctorName = user?.name || 'Dr. Sarah Jenkins';

  const handleAck = (alertId: string) => {
    acknowledgeAlert(alertId, doctorName);
    toast.success('Alert acknowledged.');
  };

  const handleResolve = (alertId: string) => {
    acknowledgeAlert(alertId, doctorName);
    toast.success('Alert resolved.');
  };

  return (
    <div className="flex h-screen bg-slate-50 overflow-hidden font-sans select-none">
      <Sidebar />

      <div className="flex-1 flex flex-col min-w-0 overflow-y-auto">
        <Header title="Clinical Deterioration Alerts Center" />

        <main className="p-4 sm:p-6 space-y-6 max-w-7xl mx-auto w-full">
          {/* Header Controls */}
          <div className="card-clinical p-4 bg-white space-y-4">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-gray-100 pb-3">
              <div>
                <h2 className="text-lg font-bold text-slate-900 flex items-center">
                  <ShieldAlert className="w-5 h-5 mr-2 text-orange-600" />
                  Non-Diagnostic Advisory Deterioration Alerts
                </h2>
                <p className="text-xs text-gray-500">
                  Automated risk notifications generated by rule analysis and trend algorithms
                </p>
              </div>

              <div className="flex items-center space-x-3">
                <span className="text-xs font-bold text-gray-500">
                  {filteredAlerts.length} Active Notifications
                </span>
                {alerts.length > 0 && (
                  <button
                    onClick={() => {
                      clearAllAlerts();
                      toast.success(`Cleared all ${alerts.length} notifications!`);
                    }}
                    className="px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 font-bold text-xs rounded-lg border border-red-200 transition-all flex items-center space-x-1.5 shadow-xs active:scale-95"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    <span>Clear All Notifications</span>
                  </button>
                )}
              </div>
            </div>

            {/* Filter Bar */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">Alert Priority</label>
                <select
                  value={selectedPriority}
                  onChange={(e) => setSelectedPriority(e.target.value)}
                  className="w-full p-2 border border-gray-200 rounded-lg text-xs focus:ring-2 focus:ring-teal-500 focus:outline-hidden"
                >
                  <option value="ALL">All Priorities</option>
                  <option value="CRITICAL">Critical Priority</option>
                  <option value="HIGH">High Priority</option>
                  <option value="MEDIUM">Medium Priority</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">Alert Status</label>
                <select
                  value={selectedStatus}
                  onChange={(e) => setSelectedStatus(e.target.value)}
                  className="w-full p-2 border border-gray-200 rounded-lg text-xs focus:ring-2 focus:ring-teal-500 focus:outline-hidden"
                >
                  <option value="ALL">All Statuses</option>
                  <option value="NEW">New (Unacknowledged)</option>
                  <option value="ACKNOWLEDGED">Acknowledged</option>
                  <option value="RESOLVED">Resolved</option>
                </select>
              </div>
            </div>
          </div>

          {/* Alerts Feed */}
          <div className="space-y-4">
            {filteredAlerts.length === 0 ? (
              <div className="card-clinical p-12 bg-white text-center text-gray-400">
                <CheckCircle2 className="w-10 h-10 mx-auto text-emerald-500 mb-2 opacity-80" />
                <p className="text-sm font-bold text-slate-800">No active alerts matching your filters</p>
                <p className="text-xs text-gray-500 mt-1">All ward patients are currently monitored within safe boundaries.</p>
              </div>
            ) : (
              filteredAlerts.map((a) => {
                const patientObj = getPatientById(a.patientId);

                return (
                  <div
                    key={a.id}
                    className={`card-clinical p-5 bg-white space-y-3 border-l-4 ${
                      a.priority === 'CRITICAL' ? 'border-l-red-500' :
                      a.priority === 'HIGH' ? 'border-l-orange-500' : 'border-l-amber-500'
                    }`}
                  >
                    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
                      <div className="flex items-center space-x-3">
                        <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold ${
                          a.priority === 'CRITICAL' ? 'bg-red-100 text-red-700' :
                          a.priority === 'HIGH' ? 'bg-orange-100 text-orange-700' : 'bg-amber-100 text-amber-700'
                        }`}>
                          {a.priority} ALERT
                        </span>

                        <span className="text-xs font-bold text-slate-900">
                          {patientObj?.name || a.patientId} ({patientObj?.ward} • Bed {patientObj?.bed})
                        </span>
                      </div>

                      <div className="flex items-center space-x-2 text-xs text-gray-400 font-mono">
                        <Clock className="w-3.5 h-3.5" />
                        <span>{new Date(a.createdAt || Date.now()).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                      </div>
                    </div>

                    <div className="text-xs text-slate-700 font-medium bg-slate-50 p-3 rounded-lg border border-slate-100">
                      <strong>Clinical Reasoning:</strong> {a.summary}
                    </div>

                    <div className="flex flex-wrap items-center justify-between gap-3 pt-2 border-t border-gray-100">
                      <div className="text-xs text-gray-500">
                        Status: <strong className="text-slate-900 capitalize">{a.status}</strong>
                        {a.acknowledgedBy && <span> • Ack by: {a.acknowledgedBy}</span>}
                      </div>

                      <div className="flex items-center space-x-2">
                        {a.status === 'NEW' && (
                          <button
                            onClick={() => handleAck(a.id)}
                            className="px-3 py-1.5 bg-amber-600 hover:bg-amber-700 text-white font-bold rounded-lg text-xs transition-all flex items-center space-x-1"
                          >
                            <Check className="w-3.5 h-3.5" />
                            <span>Acknowledge</span>
                          </button>
                        )}

                        {a.status !== 'RESOLVED' && (
                          <button
                            onClick={() => handleResolve(a.id)}
                            className="px-3 py-1.5 bg-emerald-700 hover:bg-emerald-800 text-white font-bold rounded-lg text-xs transition-all flex items-center space-x-1"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            <span>Resolve</span>
                          </button>
                        )}

                        <button
                          onClick={() => navigate(`/doctor/patients/${a.patientId}`)}
                          className="px-3 py-1.5 bg-teal-700 hover:bg-teal-800 text-white font-bold rounded-lg text-xs transition-all flex items-center space-x-1"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          <span>Review Patient</span>
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </main>
      </div>
    </div>
  );
};
